### ISSUE TITLE
vue版考虑出吗

### ISSUE THREAD

**Issue by 1018715564** [lugia-ysstech/lugia#13]
个人从知乎过来的，浏览了一下ui设计，还是偏沉重的色调，也偏欧式粗体那种的，所以个人还是比较喜欢这种风格的，能出vue版就nice了

**Comment by hanjingboo** [comment]
@1018715564 我们把React的场景打磨成熟后会考虑适配 Vue 的，哈哈😄

**Comment by zenjava** [comment]
> 个人从知乎过来的，浏览了一下ui设计，还是偏沉重的色调，也偏欧式粗体那种的，所以个人还是比较喜欢这种风格的，能出vue版就nice了

对于风格这块，因为，我们封装的组件库本身是支持主题风格配置的。后续，我们会推出组件主题配置功能，也就是在开发之前对所有组件的风格进行配置，然后再进行相应的页面设计。当然，我们得设计师，也会陆续推出几套常用的风格。

**Comment by zenjava** [comment]
> 个人从知乎过来的，浏览了一下ui设计，还是偏沉重的色调，也偏欧式粗体那种的，所以个人还是比较喜欢这种风格的，能出vue版就nice了

vue 这块的实现，后续我们会有自己的插件体系。如果你感兴趣到时可以加入我们，一起把vue引入到lugia之中。
