### ISSUE TITLE
输入项目名称被禁用

### ISSUE THREAD

**Issue by cnAlexJiang** [lugia-ysstech/lugia#15]
![image](https://user-images.githubusercontent.com/22976188/62830841-f4f66880-bc47-11e9-87da-73b9ae37d2e7.png)

**Comment by zenjava** [comment]
能发个截图么 谢谢🙏

**Comment by hanjingboo** [comment]
@cnAlexJiang 创建项目的过程需要连接网络，会从github和npm源上拉取资源，你是否可以连接到？
有报错提示信息吗？

**Comment by zenjava** [comment]
项目名称那里，你输入不了项目名称么 还是没输入项目名 直接点了创建

**Comment by hanjingboo** [comment]
在加载物料库时增加提示消息
