### ISSUE TITLE
LugiaMega.exe 下载后在内网安装，无法使用，提示：首次启动失败

### ISSUE THREAD

**Issue by yswang0927** [lugia-ysstech/lugia#17]
LugiaMega.exe 下载后在内网安装，无法使用，提示：首次启动失败。
首次启动需要连接互联网吗？

**Comment by zenjava** [comment]
我这边测试的情况是mac是不需要互联网环境， windows有些系统是需要互联网环境。  你可以看下安装目录下面的，Resouce/bin/mega/node_modules/是否存在一个.bin目录。 还有，就是创建项目的时候，因为项目的骨架还有依赖包是从npm社区的淘宝源拉取的，所以是需要网络的。 
如果安装还有遇到问题，及时联系。

**Comment by zenjava** [comment]
@yswang0927 可以随时联系我们，安装若有问题。
