### ISSUE TITLE
lugia npm install failed

### ISSUE THREAD

**Issue by JokerOrSlayer** [lugia-ysstech/lugia#28]
`npm install` error message:

```
npm ERR! path D:\lugia-master\node_modules\@lugia\devtools-material\bin\create.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\lugia-master\node_modules\@lugia\devtools-material\bin\create.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

npm registry=https://registry.npmjs.org/

**Comment by JokerOrSlayer** [comment]
切换淘宝镜像也是同样的报错：
```
D:\lugia-master>cnpm install
- [20/21] Installing semver@^5.3.0platform unsupported @lugia/mega-scripts@1.4.1 › babel-plugin-add-module-exports@1.0.2 › chokidar@2.1.6 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(win32)
\ [20/21] Installing package-json@^4.0.0[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(win32)
× Install fail! Error: ENOENT: no such file or directory, chmod 'D:\lugia-master\node_modules\_@lugia_devtools-material@1.0.32@@lugia\devtools-material\bin\create.js'
Error: ENOENT: no such file or directory, chmod 'D:\lugia-master\node_modules\_@lugia_devtools-material@1.0.32@@lugia\devtools-material\bin\create.js'
```

**Comment by hanjingboo** [comment]
@JokerOrSlayer  How did you use Lugia?

**Comment by hanjingboo** [comment]
你没有使用 客户端 建项目吗

**Comment by hanjingboo** [comment]
> 切换淘宝镜像也是同样的报错：
> 
> ```
> D:\lugia-master>cnpm install
> - [20/21] Installing semver@^5.3.0platform unsupported @lugia/mega-scripts@1.4.1 › babel-plugin-add-module-exports@1.0.2 › chokidar@2.1.6 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(win32)
> \ [20/21] Installing package-json@^4.0.0[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(win32)
> × Install fail! Error: ENOENT: no such file or directory, chmod 'D:\lugia-master\node_modules\_@lugia_devtools-material@1.0.32@@lugia\devtools-material\bin\create.js'
> Error: ENOENT: no such file or directory, chmod 'D:\lugia-master\node_modules\_@lugia_devtools-material@1.0.32@@lugia\devtools-material\bin\create.js'
> ```

**Comment by JokerOrSlayer** [comment]
其实有个疑问：`LugiaMega Setup 1.1.2.exe`  lugia 这两个的关系是什么？

必须要下载 LugiaMega Setup 1.1.2.exe 才可以运行么？

因为lugia没有安装成功，以下这些命令不知道是何效果：
```
 "scripts": {
    "lintfix": "eslint --fix ./src",
    "create": "node ./src/widgets/create.js && npm run lintfix",
    "start": "lugia-scripts start",
    "build": "lugia-scripts build",
    "test": "lugia-scripts test -w",
    "flow": "flow",
    "flow-typed": "flow-typed",
    "reset-flow-typed": "npx shx rm -rf flow-typed/npm && flow-typed install --overwrite || true"
  }
```
麻烦帮忙解答下 create 和 start 的区别

**Comment by hanjingboo** [comment]
@JokerOrSlayer 这个项目只是 Lugia 的官方网站，LugiaMega Setup 1.1.2.exe 是一个设计开发工具，是一个桌面应用

**Comment by hanjingboo** [comment]
@JokerOrSlayer 你应该下载使用 LugiaMega Setup 1.1.2.exe
