### ISSUE TITLE
Lugia mac 1.1.3 安装失败

### ISSUE THREAD

**Issue by phobal** [lugia-ysstech/lugia#32]
![image](https://user-images.githubusercontent.com/9244211/63396720-9c1e9100-c3fa-11e9-9bd7-9aa64169d358.png)

system version： 10.14.4

**Comment by hanjingboo** [comment]
@phobal 你的应用安装目录怎么这么长，它似乎是一个私有的路径？不允许写入文件？

**Comment by hanjingboo** [comment]
@phobal 你有安装过以前的版本吗，1.1.2 也有这个问题吗？

**Comment by phobal** [comment]
@hanjingboo 第一次安装，安装路径使用的默认的

**Comment by hanjingboo** [comment]
@phobal 安装路径的权限应该是可读可写的，它一般是这样的：
![image](https://user-images.githubusercontent.com/18557628/63407273-afdbee80-c41e-11e9-810a-1f9d32b1609e.png)

**Comment by hanjingboo** [comment]
@phobal 我不知道是我这边的问题还是你的安装路径有问题？

**Comment by phobal** [comment]
@hanjingboo 
卸载重新安装了 2 次，突然就好了，比较迷
