### ISSUE TITLE
开源的目的是什么?

### ISSUE THREAD

**Issue by fantasthu** [lugia-ysstech/lugia#33]
这种体验开源,是为了冲kpi么,兄弟.确实有点失望

**Comment by hanjingboo** [comment]
@fantasthu 开源的意义在于不断的迭代改进产品，在社区中产生影响力，我想这也是大部分开源项目的初衷。如果你在用的过程中有什么意见建议，欢迎你提 issues，提 pr。

**Comment by zenjava** [comment]
@fantasthu 如果持续关注我们，会发现我们在迭代我们的产品。
