### ISSUE TITLE
关于官方跳转的问题

### ISSUE THREAD

**Issue by busyRobots** [lugia-ysstech/lugia#48]
### 资源：

访问的官网地址为：http://lugia.tech/#/
### 背景：
在访问官网的lugia-web的章节时，想通过点击右侧导航栏，宽度定位到想看的组件的示例，发现跳转有问题
### 步骤描述：
* **第一步：**  打开官网访问，lugia-web的组件
* **第二步：**  通过左侧菜单选择相关的组件（我选了Navmenu、Pagination等几个，目测好像都有这个问题），点击右侧的定位导航，即可触发；
* **现象：**  页面直接跳转会首页http://lugia.tech/#/home

感觉很不友好，对于访问一些，说明多的组件，很不方便，例如Progress；

**Comment by SleepyAries** [comment]
问题已修复
