### ISSUE TITLE
智能布局功能

### ISSUE THREAD

**Issue by zenjava** [lugia-ysstech/lugia#49]
组件能自动根据屏幕比例进行缩放，支持针对四个角进行组件定位。

**Comment by zenjava** [comment]
已实现

**Comment by ly525** [comment]
您好，请问这个 issue 对应的代码能在哪里看到吗？
项目很棒，但是没有 ChangeLog，发release 的 release log 中，无法看到每次的 feature 对应的代码是哪里？请问这个可以优化下吗？

推荐使用 semantic-release 来根据 commit message 来做 change log
