### ISSUE TITLE
第一次安装lugia是成功的，后来创建项目不成功，以为是安装失败，故进行卸载，从此再也安装不成功了，每次都会提示首次启动失败，请问什么原因，我的系统是windows7

### ISSUE THREAD

**Issue by fireWinters** [lugia-ysstech/lugia#52]

**Comment by zenjava** [comment]
你的版本是1.1.4吗？还是更早的版本。

**Comment by fireWinters** [comment]
是1.1.4，昨天刚下载的，从官网上。

**Comment by grguang** [comment]
请问您那边有详细的报错信息吗？方便截图发一份吗？

**Comment by fireWinters** [comment]
您好。我的版本是1.1.4，已联系相关开发人员，但是我这里无法更新到相关补丁版本1.1.5，还原物料源和更新软件本身，一直提示是最新版本，创建项目仍然是失败的。








------------------ 原始邮件 ------------------
发件人: "liguoxin"<notifications@github.com>; 
发送时间: 2019年10月30日(星期三) 凌晨1:54
收件人: "lugia-ysstech/lugia"<lugia@noreply.github.com>; 
抄送: "念兮"<1987567948@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lugia-ysstech/lugia] 第一次安装lugia是成功的，后来创建项目不成功，以为是安装失败，故进行卸载，从此再也安装不成功了，每次都会提示首次启动失败，请问什么原因，我的系统是windows7 (#52)




你的版本是1.1.4吗？还是更早的版本。
