### ISSUE TITLE
关于lugia在使用过程中，一些问题与疑问

### ISSUE THREAD

**Issue by wsad123456pm** [lugia-ysstech/lugia#61]
1.admin页面相关功能如何开发
 - 现有lugia-admin内置的页面，如果内置admin页面不能支持一些操作，比如设置，个人中心等，如何添加功能或者更换admin页面？

2.换肤，国际化功能如何添加到现有组件中
 - 如果需求需要不同颜色的系统肤色，现有换肤的需求，lugia是否考虑了为换肤/国际化等全局操作，留有接口？

3.导航配置
 - 导航能否自定义配置，比如整个导航的收起展开，一二三多级菜单收起展开展示形式（内嵌/垂直/水平）等

4.登录页面是否有相关沉淀
 - 是否有登录页面？因现有后台包含验证码&权限等需求，是否有相关解决方案？

5.使用相关：

    5.1进入项目后需重新选择界面大小新建页面，如果不选择，拖拽组件会出问题，在项目搭建时已经选了一次，为什么需要选两次呢？
    
    5.2model管理中的新建model按钮点击后无响应，这个不是页面级别的model操作么？后期看视频才发现，新建model前面的那个输入框，是需要自己写页面名称，才能关联到对应页面的，为什么要是输入框呢，设计的有些反人类呀，下拉框不可以么？还是没有考虑用户的使用习惯？

    5.3生成组件后，没有绑定model时，暂无数据界面能否把组件内部也展示出来，我选择一个多选菜单，直接就一个白底正方形，垂直居中的暂无数据字段，组件能不能也展示出一个初始版本呢？

    5.4图片上传组件，上传图片后没有相关提示信息。

    5.5界面没有做超出部分的设置，组件可以随意拖动到页面之外。

    5.6右侧操作区域下拉框展开后，收起困难，使人会有些疑惑，到底选中与否。

    5.7组件没有重叠判断逻辑，如表格上方不应有其他组件等判断。

   5.8卡顿问题，组件拖动过程中，时不时会出现停顿在原地不动的现象。

    5.9占用内存太高，有些双核机器运行内存不高（联想T系某些机器为代表，所谓高性能实际是双核四线程，很是难受）带不动这么大的编辑器。

    5.10管理员账号页面，是否可以同时在多个ip下打开的，是否支持还是需要后续扩展？

    5.11对window系统是否支持力度不够，我在mac下使用只是有些卡顿，有时候会崩溃，用台式的时候就会出现打不开mega，创建项目卡死等问题，能否改善这些问题呢？

    5.12走马灯或者叫轮播图，里面的图片如何添加？按钮如何修改自定义的样式？

    5.13这些组件是如何封装的？是否支持二次开发？

    5.14有些组件双击可以改字段，那暂无数据的组件是怎么添加数据的呢？

    5.15拖动组件时，编辑器下方的X，Y轴数值是在点击拖动后松开鼠标时进行重新赋值的，那我点击键盘左右键控制的时候，X，Y值是不变的，而且组件拖动期间它与整个背景边界产生的标注线，也是时有时无，有时有左边距，有时有上边距，使用起来很难受，他俩不能同时存在么，或者说鼠标点击选中时上下左右标注线，不能同时存在？与其他组件的标注线能更灵活一些么？

    5.16图标按钮中的icon如何替换为真实的图片或者UI设计的非lugia的字体图片？只能使用lugia提供的icon？图标如何放大？

    总结：易用性，健壮性感觉都不高，用户体验也是，有时候感觉有些反人类。。。没有数据的组件预览之后，就是一个白色背景灰色阴影的长方形元素。。。也不清楚在哪加数据。。。新建model无效。。。后期还是朋友说的，看知乎上的视频，才知晓一些很别扭的操作，也没有交互，如果拖拽出一个组件，不绑定数据，哪怕启动项目之后，在浏览器中也是一块空白，都不知道哪个组件是谁谁谁。。。而且好像都功能单一，表格我想要分页功能，自带的与我想要的不一致，我不能通过api或者css来调整，都重新再写个组件的话，提高效率从何谈起呢？我的一些UI朋友试用之后，觉得修改东西比重新做都难。何时能解决上面提到的相关问题呢？

**Comment by zenjava** [comment]
谢谢你的意见，因为提的问题比较多，我们会就上面的问题开会讨论分析给出解决方案。

**Comment by zenjava** [comment]
我们v1.3.0的版本发布了，你可以体验以下。
