### ISSUE TITLE
【官网展示问题】固钉Affix 组件，跟随滚动轴移动

### ISSUE THREAD

**Issue by busyRobots** [lugia-ysstech/lugia#62]
**bug复现步骤**
* 打开官网，进入固钉Affix 组件，滚动查看组件构成

**bug场景见下图**
![image](https://user-images.githubusercontent.com/15335914/68933194-20509c80-07cf-11ea-8026-da7c14a38123.png)

**Comment by grguang** [comment]
您好，affix 固钉的功能就是滚动滚动条的时候固定在窗口或指定元素的指定位置。或许我没有理解到您说的bug，您可以详细说下。感谢

**Comment by busyRobots** [comment]
正如我上面截图中提到；参看我下方的这个截图，应该更加明显一些，；

affix 固钉 按钮中，的第一项中的最上面的那个 组件，是fixed， 所以他会在滚轮轴滚动和时候，被放置在页面的顶部，导致了这个问题，期望修改 @grguang 
![image](https://user-images.githubusercontent.com/15335914/69397295-9ea5c500-0d20-11ea-90ef-1e256cba5ac1.png)


![image](https://user-images.githubusercontent.com/15335914/69397224-60100a80-0d20-11ea-89db-2208fec060b5.png)

**Comment by grguang** [comment]
这个组件的功能就是 fixed 在窗口的，为了按钮在滚动滚动条的时候不会消失，一直固定在窗口那个位置

**Comment by busyRobots** [comment]
哦哦哦，明白了，感谢解答
