### ISSUE TITLE
根本就安装不上呢

### ISSUE THREAD

**Issue by wittech** [lugia-ysstech/lugia#68]
$ npm i @lugia/mega-scripts
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @lugia/lugiad-loader@^1.2.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@lugia/mega-webpack'
npm ERR! notarget

**Comment by wittech** [comment]
yarn add v1.7.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
Couldn't find any versions for "@lugia/lugiad-loader" that matches "^1.2.4"
? Please choose a version of "@lugia/lugiad-loader" from this list: (Use arrow k
eys)
❯ 1.2.4-alpha.0 
  1.2.3 
  1.2.3-alpha-0 
  1.2.2 
  1.2.2-alpha-1 
  1.2.2-alpha-0 
  1.2.1 
  1.2.1-alpha.0 
  1.2.0 
  1.2.0-alpha.1 
  1.2.0-alpha.0 
  1.1.0 
  1.0.15

**Comment by grguang** [comment]
请问您是在安装这个lugia项目依赖的时候装不上呢，还是单独安装@lugia/mega-scripts安装不上呢？如果是当前这个项目的话，建议您用yarn 安装试下。

**Comment by grguang** [comment]
这个问题修复好了，您可以安装了，如果还是失败的话，建议您将项目中yarn.lock或package.lock.json文件删除后安装。
