### ISSUE TITLE
哪里可以查找lugia-mega的详细操作手册

### ISSUE THREAD

**Issue by seelecpt** [lugia-ysstech/lugia#73]
学习资料偏少，还有是否有在线的群或者讨论可以交流？

**Comment by zenjava** [comment]
你好，我们的用户手册地址是，可能门户的图标不够清晰，后面我们改进下。

这是我们官方的QQ群。
![image](https://user-images.githubusercontent.com/12181571/72028635-330ebb80-32be-11ea-9bf8-bd8339e7645b.png)
